import Head from "next/head";
import Image from "next/image";

import { useState, useEffect } from "react";

import { Flex, Box, Heading } from "@chakra-ui/react";
import { motion, Reorder } from "framer-motion";
import NextLink from "next/link";
import { getArticles } from "../lib/getArticles.mjs";

import { PostList } from "../components/PostList";

export const getStaticProps = async () => {
	const data = await getArticles();

	return {
		props: {
			posts: data,
		},
	};
};

export default function Home({ posts }) {
	return (
		<>
			<Head>
				<title>暇な人の技術ブログ</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Heading
				as="h1"
				py="50"
				textAlign="center"
				style={{ "font-family": "'Stick', 'sans-serif'" }}
				color="gray.700"
				className="font-stick"
			>
				暇な人の技術ブログ（仮）
			</Heading>

			<iframe
				src="https://my.spline.design/untitled-0c6de592cab87ad982995bcc80ecdcb8/"
				frameborder="0"
				width="100%"
				height="500px"
				className="spline-script"
			></iframe>

			<PostList posts={posts} />
		</>
	);
}
